import argparse
from pathlib import Path

def create_new_bot(name: str):
    bot_dir = Path(name)
    bot_dir.mkdir(parents=True, exist_ok=True)
    (bot_dir / "bot.py").write_text(
        """from rlbot.agents.base_agent import BaseAgent\n\n\nclass MyBot(BaseAgent):\n    def get_output(self, packet):\n        return None\n"""
    )
    (bot_dir / "rlbot.cfg").write_text(
        """[RLBot]\n# Minimal config generated by bot_maker\n"""
    )


def main(argv=None):
    parser = argparse.ArgumentParser(description="Bot project scaffolding tool")
    sub = parser.add_subparsers(dest="command")
    new_p = sub.add_parser("new", help="Create a new bot project")
    new_p.add_argument("name", help="Folder name for the new bot")
    args = parser.parse_args(argv)

    if args.command == "new":
        create_new_bot(args.name)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
